"""Add is_visible to Vendor

Revision ID: 34bdbf7ef7b7
Revises: 45104716bcec
Create Date: 2026-01-16 20:18:27.215382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34bdbf7ef7b7'
down_revision: Union[str, None] = '45104716bcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
