"""Add duration_minutes to Service

Revision ID: 45104716bcec
Revises: 0a1a1695b064
Create Date: 2026-01-16 19:50:19.684785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45104716bcec'
down_revision: Union[str, None] = '0a1a1695b064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###
